from __future__ import annotations

from typing import Any


PRACTICE_CATEGORIES: list[dict[str, Any]] = [
    {
        "value": "internet",
        "label": "互联网行业",
        "description": "高并发、低延迟、增长指标、内容安全、多端体验和项目深挖。",
        "subjects": ["project", "system_design", "algorithm", "backend", "frontend", "database", "security"],
    },
    {
        "value": "ai_application",
        "label": "AI 应用 / 大模型",
        "description": "RAG、Agent Harness、AgentOps、搜索、多 Agent、工作流、长任务和质量评估。",
        "subjects": [
            "rag",
            "agent_harness",
            "agentops",
            "search",
            "multi_agent",
            "workflow",
            "async_workflow",
            "long_running_tasks",
            "evaluation",
        ],
    },
    {
        "value": "ecommerce",
        "label": "电商 / 本地生活",
        "description": "商品搜索、智能导购、客服助手、交易转化、履约售后和营销合规。",
        "subjects": ["search", "recommendation", "customer_service", "risk_control", "system_design"],
    },
    {
        "value": "fintech",
        "label": "金融科技",
        "description": "金融知识库、风控、合规、投研、审计、权限和高可靠。",
        "subjects": ["rag", "risk_control", "compliance", "audit", "system_design"],
    },
    {
        "value": "enterprise_saas",
        "label": "企业 SaaS / ToB",
        "description": "多租户、RBAC、企业知识库、工作流、审计、系统集成和私有化交付。",
        "subjects": ["multi_tenant", "rbac", "workflow", "integration", "audit"],
    },
    {
        "value": "civil_service",
        "label": "考公 / 公职考试",
        "description": "行测、申论、结构化面试和材料分析。",
        "subjects": ["xingce", "shenlun", "interview"],
    },
]


PRACTICE_LEARNING_PLAN: list[dict[str, Any]] = [
    {
        "stage": "基础诊断",
        "title": "先确定训练类型和能力短板",
        "description": "把目标拆成面试表达、知识点刷题、真题复盘三个层面，先建立正确率和回答质量基线。",
        "tasks": ["先选择和面试配置一致的面试类型", "记录每题耗时和错因", "把错因分为知识点、表达、方法、时间不足"],
    },
    {
        "stage": "模块训练",
        "title": "按题型建立方法库",
        "description": "刷题科目跟随面试类型拆分：互联网看工程与项目，AI 应用看 RAG/Agent/评测，电商看搜索导购交易，金融看合规风控审计，ToB 看多租户权限集成，考公看行测申论结构化。",
        "tasks": ["每类题沉淀答题模板", "把高频知识点做成错题集", "同一题型连续练到稳定再切换"],
    },
    {
        "stage": "表达提升",
        "title": "从会做到会讲",
        "description": "刷题不是终点，最终要把答案组织成面试能听懂、能追问、能验证的表达。",
        "tasks": ["先讲结论，再讲依据", "训练分条作答和关键词前置", "每次复盘都补充一个具体案例或指标"],
    },
    {
        "stage": "冲刺复盘",
        "title": "限时训练和错题回炉",
        "description": "使用自有题库、历年真题或合法授权题源做限时训练，复盘比刷题数量更重要。",
        "tasks": ["每周至少一次限时训练", "错题 24 小时内复做", "建立高频考点和易错方法清单"],
    },
]

CIVIL_SERVICE_LEARNING_PLAN = PRACTICE_LEARNING_PLAN


CIVIL_SERVICE_SEED_QUESTIONS: list[dict[str, Any]] = [
    {
        "source": "built_in_sample",
        "practice_category": "civil_service",
        "exam_year": 2026,
        "exam_name": "考公行测训练样题",
        "subject": "xingce",
        "question_type": "言语理解",
        "prompt": "某地推进政务服务数字化改革，材料强调既要让群众少跑腿，也要避免老年群体因不会使用智能设备而办事困难。最适合概括该材料主旨的是：",
        "choices": ["数字化改革应追求技术领先", "政务服务要兼顾效率与包容性", "老年群体不适合使用线上服务", "线下窗口会降低行政效率"],
        "answer": "B",
        "explanation": "材料同时强调少跑腿和避免数字鸿沟，核心是效率与包容并重。",
        "difficulty": "easy",
        "tags": ["政务服务", "主旨概括", "数字鸿沟"],
    },
    {
        "source": "built_in_sample",
        "practice_category": "civil_service",
        "exam_year": 2026,
        "exam_name": "考公行测训练样题",
        "subject": "xingce",
        "question_type": "判断推理",
        "prompt": "所有基层治理创新都需要群众参与。有些数字治理项目属于基层治理创新。据此可以推出：",
        "choices": ["所有数字治理项目都需要群众参与", "有些数字治理项目需要群众参与", "没有群众参与就没有数字治理", "基层治理创新都属于数字治理项目"],
        "answer": "B",
        "explanation": "有些数字治理项目属于基层治理创新，而所有基层治理创新都需要群众参与，因此有些数字治理项目需要群众参与。",
        "difficulty": "medium",
        "tags": ["逻辑判断", "三段论", "基层治理"],
    },
    {
        "source": "built_in_sample",
        "practice_category": "civil_service",
        "exam_year": 2026,
        "exam_name": "考公申论训练样题",
        "subject": "shenlun",
        "question_type": "归纳概括",
        "prompt": "请根据给定材料，概括某县推进乡村公共服务均等化的主要做法。要求：全面、准确、有条理，不超过 200 字。",
        "choices": [],
        "answer": "从基础设施、服务下沉、数字平台、群众参与、长效机制等方面概括。",
        "explanation": "申论概括题要紧扣材料，按同类合并原则提炼关键词，并避免脱离材料发挥。",
        "difficulty": "medium",
        "tags": ["申论", "归纳概括", "公共服务"],
    },
]


INTERNET_SEED_QUESTIONS: list[dict[str, Any]] = [
    {
        "source": "built_in_sample",
        "practice_category": "internet",
        "exam_year": 2026,
        "exam_name": "互联网技术面试训练样题",
        "subject": "system_design",
        "question_type": "系统设计",
        "prompt": "设计一个短链服务。请说明核心表结构、生成算法、跳转链路、缓存策略、风控和高并发下的可用性设计。",
        "choices": [],
        "answer": "围绕短码生成、唯一性、重定向读多写少、缓存、限流、黑名单、监控和降级展开。",
        "explanation": "系统设计题重点不是背方案，而是讲清楚业务约束、核心路径、数据模型、容量估算和故障处理。",
        "difficulty": "medium",
        "tags": ["系统设计", "高并发", "缓存", "风控"],
    },
    {
        "source": "built_in_sample",
        "practice_category": "internet",
        "exam_year": 2026,
        "exam_name": "互联网技术面试训练样题",
        "subject": "project",
        "question_type": "项目深挖",
        "prompt": "请用 STAR 结构讲一个你主导排查线上故障的案例，重点说明定位路径、数据证据、止血动作和复盘改进。",
        "choices": [],
        "answer": "需要覆盖背景、任务、行动、结果，并补充监控指标、日志证据、回滚/降级和后续机制建设。",
        "explanation": "项目深挖题要体现真实工程经验，回答里最好有指标、个人职责、关键判断和复盘闭环。",
        "difficulty": "medium",
        "tags": ["项目深挖", "线上故障", "稳定性", "STAR"],
    },
    {
        "source": "built_in_sample",
        "practice_category": "internet",
        "exam_year": 2026,
        "exam_name": "互联网后端面试训练样题",
        "subject": "backend",
        "question_type": "后端工程",
        "prompt": "一个接口偶发超时，你会如何从客户端、网关、应用、数据库、缓存和第三方依赖逐层定位？请说明你会看哪些指标和日志。",
        "choices": [],
        "answer": "从请求链路、trace id、网关耗时、应用日志、慢 SQL、缓存命中率、线程池/连接池、第三方耗时和错误率逐层排查。",
        "explanation": "后端排障题重点是链路化定位，而不是只说看日志。最好能讲出指标、证据和止血手段。",
        "difficulty": "medium",
        "tags": ["后端", "排障", "链路追踪", "性能"],
    },
    {
        "source": "built_in_sample",
        "practice_category": "internet",
        "exam_year": 2026,
        "exam_name": "互联网前端面试训练样题",
        "subject": "frontend",
        "question_type": "前端工程",
        "prompt": "首屏加载很慢，你会如何优化？请从资源体积、缓存、网络、渲染、代码拆分和监控指标说明。",
        "choices": [],
        "answer": "可以从 bundle 分析、懒加载、CDN、HTTP 缓存、图片优化、SSR/预渲染、减少阻塞脚本、LCP/FCP/INP 指标监控回答。",
        "explanation": "前端性能题要结合用户体验指标和工程手段，避免只回答压缩代码。",
        "difficulty": "medium",
        "tags": ["前端", "性能优化", "首屏", "监控"],
    },
    {
        "source": "built_in_sample",
        "practice_category": "internet",
        "exam_year": 2026,
        "exam_name": "互联网数据库面试训练样题",
        "subject": "database",
        "question_type": "数据库设计",
        "prompt": "订单表数据量很大，查询变慢。你会如何设计索引、分库分表、冷热分层和归档策略？",
        "choices": [],
        "answer": "需要结合查询模式设计联合索引，评估分页方式、读写分离、分区/分表、冷热数据、归档任务和迁移风险。",
        "explanation": "数据库题不能只说加索引，要结合业务查询、写入成本、数据生命周期和运维复杂度。",
        "difficulty": "hard",
        "tags": ["数据库", "索引", "分表", "归档"],
    },
    {
        "source": "built_in_sample",
        "practice_category": "internet",
        "exam_year": 2026,
        "exam_name": "互联网算法面试训练样题",
        "subject": "algorithm",
        "question_type": "算法思维",
        "prompt": "给定一个字符串，找出不含重复字符的最长子串长度。请说明滑动窗口思路、复杂度和边界情况。",
        "choices": [],
        "answer": "使用左右指针和哈希表记录字符最近位置，遇到重复字符移动左边界，时间复杂度 O(n)，空间复杂度 O(k)。",
        "explanation": "算法题面试时要先讲清楚状态、窗口移动条件、复杂度，再写代码。",
        "difficulty": "medium",
        "tags": ["算法", "滑动窗口", "哈希表"],
    },
    {
        "source": "built_in_sample",
        "practice_category": "internet",
        "exam_year": 2026,
        "exam_name": "互联网安全面试训练样题",
        "subject": "security",
        "question_type": "应用安全",
        "prompt": "你会如何防止登录接口被撞库和暴力破解？请从限流、验证码、设备指纹、风控、告警和用户体验说明。",
        "choices": [],
        "answer": "可设计账号/IP/设备维度限流、失败次数策略、验证码/二次验证、风险评分、黑名单、审计日志、告警和渐进式拦截。",
        "explanation": "安全题要体现纵深防御和误伤控制，不能只靠单一验证码。",
        "difficulty": "hard",
        "tags": ["安全", "风控", "限流", "登录"],
    },
]


COMMON_INTERVIEW_BASE_QUESTIONS: list[dict[str, Any]] = [
    {
        "source": "built_in_sample",
        "exam_year": 2026,
        "exam_name": "通用表达训练样题",
        "subject": "behavioral",
        "question_type": "行为面试",
        "prompt": "请讲一个你和他人意见不一致但最终推动事情落地的案例。你如何沟通、取舍和复盘？",
        "choices": [],
        "answer": "可以用 STAR 结构回答，突出目标一致、事实依据、方案比较、沟通动作、结果和复盘。",
        "explanation": "行为面试题要避免泛泛而谈，需要讲真实冲突、个人动作和可验证结果。",
        "difficulty": "medium",
        "tags": ["行为面试", "沟通协作", "STAR"],
    },
    {
        "source": "built_in_sample",
        "exam_year": 2026,
        "exam_name": "通用表达训练样题",
        "subject": "general",
        "question_type": "自我介绍",
        "prompt": "请做一个 2 分钟自我介绍，要求结合目标岗位突出你的项目经验、核心能力和求职动机。",
        "choices": [],
        "answer": "建议按背景、核心项目、能力标签、岗位匹配和动机收尾组织。",
        "explanation": "自我介绍要服务于目标岗位，重点不是简历流水账，而是建立面试官继续追问的线索。",
        "difficulty": "easy",
        "tags": ["自我介绍", "岗位匹配", "表达"],
    },
]


COMMON_INTERVIEW_SEED_QUESTIONS: list[dict[str, Any]] = [
    {**question, "practice_category": category["value"], "exam_name": f"{category['label']}通用表达训练样题"}
    for category in PRACTICE_CATEGORIES
    for question in COMMON_INTERVIEW_BASE_QUESTIONS
]


AI_ENGINEERING_SEED_QUESTIONS: list[dict[str, Any]] = [
    {
        "source": "built_in_sample",
        "practice_category": "ai_application",
        "exam_year": 2026,
        "exam_name": "AI 工程面试训练样题",
        "subject": "rag",
        "question_type": "RAG 项目深挖",
        "prompt": "你做过的 RAG 系统如何处理召回不准和幻觉问题？请说明切分、向量召回、重排、引用校验、评测指标和线上观测。",
        "choices": [],
        "answer": "可从 chunk 策略、混合检索、rerank、答案引用、拒答机制、离线评测集、线上反馈闭环等角度回答。",
        "explanation": "AI 工程题要避免只讲概念，需要落到数据、评测、上线和安全治理。",
        "difficulty": "hard",
        "tags": ["RAG", "召回", "评测", "幻觉治理"],
    },
    {
        "source": "built_in_sample",
        "practice_category": "ai_application",
        "exam_year": 2026,
        "exam_name": "AI 工程面试训练样题",
        "subject": "agent_harness",
        "question_type": "Agent 设计",
        "prompt": "如果要设计一个可调用工具的 Agent，你会如何做权限控制、工具选择、失败重试、成本控制和审计日志？",
        "choices": [],
        "answer": "重点覆盖工具白名单、参数校验、最小权限、计划执行、超时重试、预算上限、人工确认和全链路审计。",
        "explanation": "Agent 不是只让模型调用函数，还要把安全边界、可观测性和成本治理设计进去。",
        "difficulty": "hard",
        "tags": ["Agent", "工具调用", "权限", "审计"],
    },
    {
        "source": "built_in_sample",
        "practice_category": "ai_application",
        "exam_year": 2026,
        "exam_name": "AI 工程面试训练样题",
        "subject": "agent_harness",
        "question_type": "Agent Harness",
        "prompt": "请设计一个 Agent Harness，用来统一管理模型调用、工具执行、上下文注入、护栏、可观测性和回放调试。你会如何拆模块？",
        "choices": [],
        "answer": "可以按模型适配层、工具注册与权限、上下文构造、执行状态机、guardrail、trace 日志、回放评测和成本统计拆分。",
        "explanation": "Agent Harness 的重点是把一次 Agent 运行变成可控、可审计、可回放、可评测的工程系统。",
        "difficulty": "hard",
        "tags": ["Agent Harness", "工具编排", "可观测性", "回放调试"],
    },
    {
        "source": "built_in_sample",
        "practice_category": "ai_application",
        "exam_year": 2026,
        "exam_name": "AI 工程面试训练样题",
        "subject": "agentops",
        "question_type": "AgentOps",
        "prompt": "Agent 上线后经常出现工具失败、循环调用、成本失控和结果不稳定。你会如何设计 AgentOps 平台来监控、告警、限流和回滚？",
        "choices": [],
        "answer": "需要覆盖 trace/span、工具成功率、循环检测、预算上限、异常聚合、灰度发布、人工接管、回滚策略和评测看板。",
        "explanation": "AgentOps 强调运行期治理，不只是日志采集，还要能定位、止血、评估和持续改进。",
        "difficulty": "hard",
        "tags": ["AgentOps", "监控", "告警", "成本治理", "灰度"],
    },
    {
        "source": "built_in_sample",
        "practice_category": "ai_application",
        "exam_year": 2026,
        "exam_name": "AI 工程面试训练样题",
        "subject": "search",
        "question_type": "搜索系统",
        "prompt": "如果要为企业知识库做 AI 搜索，你会如何设计关键词召回、向量召回、重排、权限过滤、摘要生成和结果评估？",
        "choices": [],
        "answer": "可采用 BM25/关键词召回、向量召回、混合召回、rerank、ACL 过滤、引用式摘要、离线 NDCG/Recall 和线上点击反馈。",
        "explanation": "AI 搜索既要检索相关性，也要处理权限、安全、延迟和结果可解释性。",
        "difficulty": "hard",
        "tags": ["搜索", "混合检索", "rerank", "权限过滤", "评估"],
    },
    {
        "source": "built_in_sample",
        "practice_category": "ai_application",
        "exam_year": 2026,
        "exam_name": "AI 工程面试训练样题",
        "subject": "multi_agent",
        "question_type": "多 Agent 协作",
        "prompt": "多 Agent 协作系统里，Planner、Researcher、Executor、Critic 之间如何通信和收敛？如何避免互相甩锅、无限循环和上下文爆炸？",
        "choices": [],
        "answer": "可以设计角色边界、共享任务状态、消息协议、最大轮次、检查点、仲裁器、上下文摘要和失败降级机制。",
        "explanation": "多 Agent 的难点是协调成本和可控性，面试中要讲清楚协议、状态、终止条件和观测手段。",
        "difficulty": "hard",
        "tags": ["多 Agent", "协作协议", "终止条件", "上下文治理"],
    },
    {
        "source": "built_in_sample",
        "practice_category": "ai_application",
        "exam_year": 2026,
        "exam_name": "AI 工程面试训练样题",
        "subject": "workflow",
        "question_type": "复杂任务编排",
        "prompt": "设计一个支持复杂 AI 任务编排的平台：任务可以分支、重试、等待人工确认、调用外部工具，并能恢复执行。核心架构怎么做？",
        "choices": [],
        "answer": "重点包括 DAG/状态机建模、任务队列、幂等、重试策略、补偿事务、人工节点、状态持久化、可观测性和权限控制。",
        "explanation": "复杂任务编排考察的是工程平台能力，回答要覆盖状态、可靠性、恢复和外部副作用治理。",
        "difficulty": "hard",
        "tags": ["任务编排", "状态机", "幂等", "恢复执行"],
    },
    {
        "source": "built_in_sample",
        "practice_category": "ai_application",
        "exam_year": 2026,
        "exam_name": "AI 工程面试训练样题",
        "subject": "async_workflow",
        "question_type": "异步工作流",
        "prompt": "一个 AI 工作流可能运行几十分钟，期间包含模型调用、文件解析、检索、人工审核和外部 API。你会如何设计异步执行、进度通知和失败恢复？",
        "choices": [],
        "answer": "可用任务表、队列、worker、状态流转、心跳、超时、断点续跑、事件通知、SSE/Webhook 推送和幂等重试。",
        "explanation": "异步工作流要重点讲长任务状态管理和用户体验，而不是只把请求超时时间调长。",
        "difficulty": "hard",
        "tags": ["异步工作流", "长任务", "队列", "断点续跑"],
    },
    {
        "source": "built_in_sample",
        "practice_category": "ai_application",
        "exam_year": 2026,
        "exam_name": "AI 工程面试训练样题",
        "subject": "long_running_tasks",
        "question_type": "长任务执行平台",
        "prompt": "请设计一个长任务执行平台，支持取消、暂停、恢复、超时控制、资源隔离、结果归档和审计。你会如何设计数据模型和执行器？",
        "choices": [],
        "answer": "需要定义 job/run/step 表、状态机、租户隔离、worker lease、心跳续约、取消信号、结果存储、审计日志和资源配额。",
        "explanation": "长任务平台题重点是可靠性和控制面设计，要讲清楚状态一致性、worker 崩溃恢复和用户可见进度。",
        "difficulty": "hard",
        "tags": ["长任务", "执行平台", "资源隔离", "审计"],
    },
    {
        "source": "built_in_sample",
        "practice_category": "ai_application",
        "exam_year": 2026,
        "exam_name": "AI 工程面试训练样题",
        "subject": "evaluation",
        "question_type": "质量评估",
        "prompt": "如何评估一个 Agent 或 RAG 系统的质量？请设计离线评测集、自动评分、人工复核、线上指标和回归测试流程。",
        "choices": [],
        "answer": "可覆盖 golden set、任务成功率、事实一致性、引用命中、工具调用正确率、LLM-as-judge、人审抽样、A/B 和版本回归。",
        "explanation": "质量评估是 AI 工程落地核心，面试里要体现指标体系、样本构建、自动化和上线闭环。",
        "difficulty": "hard",
        "tags": ["质量评估", "RAG 评测", "Agent 评测", "回归测试"],
    },
]


ECOMMERCE_SEED_QUESTIONS: list[dict[str, Any]] = [
    {
        "source": "built_in_sample",
        "practice_category": "ecommerce",
        "exam_year": 2026,
        "exam_name": "电商 / 本地生活面试训练样题",
        "subject": "search",
        "question_type": "商品搜索",
        "prompt": "设计一个商品搜索排序系统。请说明关键词召回、向量召回、类目/价格/库存过滤、重排、个性化和线上指标。",
        "choices": [],
        "answer": "可覆盖 BM25、向量召回、混合召回、类目过滤、库存价格实时校验、rerank、个性化特征、CTR/CVR/GMV 和延迟指标。",
        "explanation": "电商搜索题要把相关性、实时业务约束和交易指标放在一起讲。",
        "difficulty": "hard",
        "tags": ["电商", "搜索", "排序", "转化"],
    },
    {
        "source": "built_in_sample",
        "practice_category": "ecommerce",
        "exam_year": 2026,
        "exam_name": "电商 / 本地生活面试训练样题",
        "subject": "customer_service",
        "question_type": "智能客服",
        "prompt": "AI 客服回答商品价格、库存和售后政策时，如何避免编造和错误承诺？请设计知识来源、实时校验、兜底和转人工策略。",
        "choices": [],
        "answer": "需要区分静态知识和实时业务数据，价格库存走实时 API，政策有版本引用，高风险话术转人工，保留审计和客诉反馈。",
        "explanation": "交易场景的 AI 答案会影响用户决策，必须强调实时数据、合规话术和责任边界。",
        "difficulty": "hard",
        "tags": ["客服助手", "实时数据", "售后", "风控"],
    },
]


FINTECH_SEED_QUESTIONS: list[dict[str, Any]] = [
    {
        "source": "built_in_sample",
        "practice_category": "fintech",
        "exam_year": 2026,
        "exam_name": "金融科技面试训练样题",
        "subject": "compliance",
        "question_type": "合规风控",
        "prompt": "金融场景下的大模型助手如何避免输出投资建议或误导性结论？请说明权限、引用、免责声明、人工复核和审计。",
        "choices": [],
        "answer": "需要限制模型边界，使用可信来源和引用，敏感问题触发免责声明和人工复核，全链路留痕审计，避免直接替代合规决策。",
        "explanation": "金融科技题重点是高风险场景治理，回答要保守、可解释、可追溯。",
        "difficulty": "hard",
        "tags": ["金融", "合规", "审计", "风险控制"],
    },
    {
        "source": "built_in_sample",
        "practice_category": "fintech",
        "exam_year": 2026,
        "exam_name": "金融科技面试训练样题",
        "subject": "rag",
        "question_type": "金融知识库",
        "prompt": "设计一个金融投研知识库 RAG。如何保证资料来源可信、版本可追溯、权限隔离和答案引用准确？",
        "choices": [],
        "answer": "可从数据来源准入、文档版本、ACL 过滤、检索引用、答案忠实度评测、审计日志和人工复核流程展开。",
        "explanation": "金融 RAG 不是普通文档问答，必须把可信来源、权限和留痕作为核心设计。",
        "difficulty": "hard",
        "tags": ["金融 RAG", "权限", "引用", "可信来源"],
    },
]


ENTERPRISE_SAAS_SEED_QUESTIONS: list[dict[str, Any]] = [
    {
        "source": "built_in_sample",
        "practice_category": "enterprise_saas",
        "exam_year": 2026,
        "exam_name": "企业 SaaS / ToB 面试训练样题",
        "subject": "multi_tenant",
        "question_type": "多租户架构",
        "prompt": "企业知识库 AI 助手如何设计多租户隔离、RBAC 权限、审计日志和私有化部署？",
        "choices": [],
        "answer": "需要覆盖租户隔离模型、用户/角色/资源权限、检索前 ACL 过滤、操作审计、配置中心、私有化部署和数据生命周期。",
        "explanation": "ToB 场景面试重点是权限、隔离、审计和交付运维，不只是功能可用。",
        "difficulty": "hard",
        "tags": ["ToB", "多租户", "RBAC", "审计"],
    },
    {
        "source": "built_in_sample",
        "practice_category": "enterprise_saas",
        "exam_year": 2026,
        "exam_name": "企业 SaaS / ToB 面试训练样题",
        "subject": "workflow",
        "question_type": "业务工作流",
        "prompt": "Agent 要调用 CRM、工单和审批系统完成业务动作。你如何设计人工确认、权限校验、失败补偿和回滚？",
        "choices": [],
        "answer": "可以设计工具白名单、参数校验、RBAC、双确认、高风险审批、幂等键、补偿任务、审计日志和失败告警。",
        "explanation": "企业 Agent 的核心是动作安全和可追责，不能让模型直接无边界操作业务系统。",
        "difficulty": "hard",
        "tags": ["Agent", "工作流", "工具调用", "补偿回滚"],
    },
]


DEFAULT_PRACTICE_QUESTIONS: list[dict[str, Any]] = [
    *INTERNET_SEED_QUESTIONS,
    *AI_ENGINEERING_SEED_QUESTIONS,
    *ECOMMERCE_SEED_QUESTIONS,
    *FINTECH_SEED_QUESTIONS,
    *ENTERPRISE_SAAS_SEED_QUESTIONS,
    *CIVIL_SERVICE_SEED_QUESTIONS,
    *COMMON_INTERVIEW_SEED_QUESTIONS,
]
