const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("interviewAgent", {
  health: () => ipcRenderer.invoke("api:health"),
  listIndustries: (targetRole) => ipcRenderer.invoke("metadata:industries", targetRole),
  listModels: () => ipcRenderer.invoke("metadata:models"),
  getCivilServiceLearningPlan: () => ipcRenderer.invoke("civil-service:learning-plan"),
  listCivilServiceQuestions: (filters) => ipcRenderer.invoke("civil-service:questions", filters),
  seedCivilServiceQuestions: () => ipcRenderer.invoke("civil-service:seed"),
  register: (payload) => ipcRenderer.invoke("auth:register", payload),
  login: (payload) => ipcRenderer.invoke("auth:login", payload),
  devLogin: (payload) => ipcRenderer.invoke("auth:dev-login", payload),
  logout: () => ipcRenderer.invoke("auth:logout"),
  getAccount: () => ipcRenderer.invoke("account:get"),
  getSettings: () => ipcRenderer.invoke("settings:get"),
  updateSettings: (payload) => ipcRenderer.invoke("settings:update", payload),
  recharge: (payload) => ipcRenderer.invoke("account:recharge", payload),
  createPaymentOrder: (payload) => ipcRenderer.invoke("payments:create-order", payload),
  getPaymentOrder: (orderId) => ipcRenderer.invoke("payments:get-order", orderId),
  listResumes: () => ipcRenderer.invoke("resumes:list"),
  getResume: (resumeId) => ipcRenderer.invoke("resumes:get", resumeId),
  deleteResume: (resumeId) => ipcRenderer.invoke("resumes:delete", resumeId),
  listSessions: () => ipcRenderer.invoke("sessions:list"),
  getSession: (sessionId) => ipcRenderer.invoke("sessions:get", sessionId),
  deleteSession: (sessionId) => ipcRenderer.invoke("sessions:delete", sessionId),
  rewindSession: (sessionId, payload) => ipcRenderer.invoke("sessions:rewind", sessionId, payload),
  importResume: () => ipcRenderer.invoke("resume:import"),
  parseDocument: () => ipcRenderer.invoke("document:parse"),
  createSession: (payload) => ipcRenderer.invoke("api:create-session", payload),
  sendMessage: (payload) => ipcRenderer.invoke("api:send-message", payload)
});
